### ISSUE TITLE
ENOTSUP: operation not supported on socket

### ISSUE THREAD

**Issue by marvc1** [welldone-software/gulp-durandal#22]
Using v1.1.7 I'm getting the following error:

`ENOTSUP: operation not supported on socket, scandir 'D:\home\site\repository\Website\wwwroot\app-built\config.js'
at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Glob._readdir (D:\home\site\repository\Website\node_modules\gulp-durandal\node_modules\glob\glob.js:662:20)
    at Glob._process (D:\home\site\repository\Website\node_modules\gulp-durandal\node_modules\glob\glob.js:446:15)
    at Glob.<anonymous> (D:\home\site\repository\Website\node_modules\gulp-durandal\node_modules\glob\glob.js:480:14)
    at Array.forEach (native)
The 'prepublish' script failed with status code 1.`

It's an issue with Glob that seems to have been fixed:
https://github.com/isaacs/node-glob/issues/205

Can we update glob please?

**Comment by marvc1** [comment]
I can submit a pull request with the update, but the tests are failing for me before and after updating glob to v6.0.4.

Also, I do not know how to update the NPM package....
